version: "3.9"
services:
  sosmed:
    image: sosmed-imsal
    ports:
    - 80:80
    environment:
      DB_HOST: "mysql"
      DB_USERNAME: "imsal"
      DB_PASSWORD: "admin123"
      DB_NAME: "db-sosmed"
    depends_on:
      - mysql
  mysql:
    image: "mysql:latest"
    container_name: sosmed-imsal
    environment:
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_USER: "imsal"
      MYSQL_PASSWORD: "admin123"
      MYSQL_DATABASE: "db-sosmed"
      MYSQL_HOST: "sosmed"
    volumes:
       - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
    - '3306:3306'
