version: "3.9"

services:
  sosialmedia:
    image: imsalyunus/sosial-media:${TAG_IMAGE}
    container_name: sosialmedia-dev
    ports:
      - 82:80
    environment:
      - DB_HOST=mysql-dev
      - DB_USER=imsalyunus
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=dbsosmed
    
    # Menjalankan service mysql dulu kemudian service sosialmedia
    depends_on:
      - mysql
  
  mysql:
    image: mysql:5.7 #https://hub.docker.com/layers/library/mysql/5.7/images/sha256-dab0a802b44617303694fb17d166501de279c3031ddeb28c56ecf7fcab5ef0da?context=explore
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=dbsosmed
      - MYSQL_USER=imsalyunus
      - MYSQL_PASSWORD=${DB_PASSWORD}
      
    # Mengimpor data dari local ke dalam MySQL yaitu data_dump.sql
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./dump.sql:/docker-entrypoint-initdb.d/data_dump.sql
    
volumes:
  mysql_data:
