version: "3.9"

services:

  sosialmedia-prod:
    image: imsalyunus/sosial-media:${TAG_IMAGE}

    container_name: sosialmedia-prod

    ports:
      - "83:80"

    environment:
      DB_HOST: mysql
      DB_USER: imsalyunus
      DB_PASS: ${DB_PASSWORD}
      DB_NAME: dbsosmed

    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dbsosmed
      MYSQL_USER: imsalyunus
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
      #- ./dump.sql:/docker-entrypoint-initdb.d/data_dump.sql



volumes:

  mysql_data:
